.rw-r--r-- maycolzx maycolzx 484 B  Fri Jun 21 18:09:56 2024 medianuva.cpp
.rw-r--r-- maycolzx maycolzx 1.7 KB Fri Jun 21 18:09:56 2024 mochila_back.cpp
.rw-r--r-- maycolzx maycolzx 1.9 KB Fri Jun 21 18:09:56 2024 secuencialetra.cpp
.rw-r--r-- maycolzx maycolzx 1.6 KB Fri Jun 21 18:09:56 2024 secuencianumeros.cpp
.rw-r--r-- maycolzx maycolzx 612 B  Fri Jun 21 18:09:56 2024 uvacoincha.cpp
.rw-r--r-- maycolzx maycolzx 1.2 KB Fri Jun 21 18:09:56 2024 whatgoesup.cpp
